### ISSUE TITLE
Adjacent Roads

### ISSUE THREAD

**Issue by Morganplant** [sussex-Team15/Settler-Project#64]
When placing Roads you can place roads from anynode to any other node, we need to make it so that this only works for adjacent nodes

A solution might be :
https://github.com/sussex-Team15/Settler-Project/blob/c15b964d9b520b9ef11ff221a79d44d31973dc6b/src/main.py#L499

**Comment by Scufedd** [comment]
which main should I work on this in?

**Comment by Morganplant** [comment]
@Scufedd @EddieJ01 @Noah-Davy I think we should stop working on `main.py` and focus our efforts on `main_refactored.py`

**Comment by Noah-Davy** [comment]
Yeah definitely, I think Eddie said he was going to delete main.py bc
main_refactored has all the functions we need from there

**Comment by EddieJ01** [comment]
- is adjacent methods have been implemented
