### ISSUE TITLE
Not Responding Error

### ISSUE THREAD

**Issue by Morganplant** [sussex-Team15/Settler-Project#74]
To Reproduce the error you can do the following steps

Enter the game with 3 players

- Step1 - Click the Build Settlement Button
- Step2 - Click on any node
- Step3 - Click on the centre of any tile (the number)
- Step4 - Click around the board randomly for around 10s

After those steps the Not Responding Error Appears for around 2 seconds then dissapears

**Comment by EddieJ01** [comment]
error no longer occurs
